apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service-app
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongo-pod-app
  type: LoadBalancer