apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo-pod-app
spec:
  volumes:
  - name: mongo-storage
    hostPath:
      path: /var/lib/docker/volumes/my-volume/_data
  containers:
  - name: my-mongo
    image: mongo
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 27017
      name: mongo-port
    volumeMounts:
    - name: mongo-storage
      mountPath: /testtwo