apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service-app
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres-pod-app
  type: LoadBalancer